# Generated by Django 3.0 on 2021-03-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogApiRequestsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256, verbose_name='Username')),
                ('url', models.CharField(max_length=256, verbose_name='Request sent to URL')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
